// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoftwareAssuranceMaturityModel.Infrastructure.Persistence;

#nullable disable

namespace SoftwareAssuranceMaturityModel.Infrastructure.Persistence.Migrations.Application
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220210042042_InitApplication")]
    partial class InitApplication
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("SoftwareAssuranceMaturityModel.Domain.Entities.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("SoftwareAssuranceMaturityModel.Domain.Entities.Respond", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QDomain")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("Responds");
                });

            modelBuilder.Entity("SoftwareAssuranceMaturityModel.Domain.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Flag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("SoftwareAssuranceMaturityModel.Domain.Entities.Batch", b =>
                {
                    b.HasOne("SoftwareAssuranceMaturityModel.Domain.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SoftwareAssuranceMaturityModel.Domain.Entities.Respond", b =>
                {
                    b.HasOne("SoftwareAssuranceMaturityModel.Domain.Entities.Batch", null)
                        .WithMany("Responds")
                        .HasForeignKey("BatchId");
                });

            modelBuilder.Entity("SoftwareAssuranceMaturityModel.Domain.Entities.Batch", b =>
                {
                    b.Navigation("Responds");
                });
#pragma warning restore 612, 618
        }
    }
}
